// ------------------------------------------------------------------------------------------------
// Training ~ A training program for new joinees at Metamation, Batch- July 2025.
// Copyright (c) Metamation India.
// ------------------------------------------------------------------
// Program.cs
// A02: Program lets the user guess the random number generated by the computer [1 - 100]
// ------------------------------------------------------------------------------------------------
using static System.Console;

int random = new Random ().Next (1, 101);
WriteLine ("Guess the number between 1 to 100");
for (; ; ) {
   Write ("Enter your guess: ");
   if (int.TryParse (ReadLine (), out int num) && num > 0 && num <= 100) {
      if (num == random) {
         WriteLine ("You guessed correctly!");
         return;
      }
      if (num > random) WriteLine ("Your guess is too high!");
      else WriteLine ("Your guess is too low!");
   } else WriteLine ("Please enter a valid integer within 1 - 100!");
}