// ------------------------------------------------------------------------------------------------
// Training ~ A training program for new joinees at Metamation, Batch- July 2025.
// Copyright (c) Metamation India.
// ------------------------------------------------------------------
// Program.cs
// A02: Program to find the random number [1 - 100] generated by the computer.
// ------------------------------------------------------------------------------------------------
using static System.Console;

do {
   Clear ();
   WriteLine ("Guess the number between 1 and 100");
   int n = new Random ().Next (1, 101), tries = 0;
   bool found = false;
   while (!found) {
      Write ("Enter your guess: ");
      if (int.TryParse (ReadLine (), out int guess)) {
         found = n == guess; tries++;
         WriteLine ($"Your guess is {(found ? $"correct with {tries} tries"
                                            : $"too {(guess > n ? "high" : "low")}")}");
      }
   }
   WriteLine ($"Press 'Y' to play again");
} while (ReadKey (true).Key == ConsoleKey.Y);