// ------------------------------------------------------------------------------------------------
// Training ~ A training program for new joinees at Metamation, Batch- July 2025.
// Copyright (c) Metamation India.
// ------------------------------------------------------------------
// Program.cs
// A02: Program lets the user guess the random number generated by the computer [1 - 100]
// ------------------------------------------------------------------------------------------------
using static System.Console;

do {
   Clear ();
   int random = new Random ().Next (1, 101);
   WriteLine ("Guess the number between 1 to 100");
   for (int tries = 1; ; tries++) {
      Write ("Enter your guess: ");
      if (uint.TryParse (ReadLine (), out uint num) && num > 0 && num <= 100) {
         if (num == random) {
            WriteLine ($"You guessed the number in {tries} tries");
            break;
         }
         WriteLine ($"Your guess is too {(num > random ? "high" : "low")}");
      } else WriteLine ("Please enter a value between 1 and 100");
   }
   Write ("Press 'Y' to play again");
} while (ReadKey (true).Key == ConsoleKey.Y);